### ISSUE TITLE
Allow for polling futures.

### ISSUE THREAD

**Issue by cheako** [zslayton/lifeguard#24]
There may be other reasons to walk the values Vec so perhaps this should be generic.  This is useful if the Pool contains sockets(TCP) where periodic pings need to be replied to, but I can think of other reasons.

**Comment by zslayton** [comment]
> This is useful if the Pool contains sockets(TCP) where periodic pings need to be replied to, but I can think of other reasons.

I believe you're describing a connection pool, something like what [the `r2d2` crate](https://crates.io/crates/r2d2) offers. In contrast, `lifeguard`'s `Pool` stores dropped values so they can be recycled rather than calling the system allocator each time you need a new one. By definition, every value in the `Pool` is not currently in use.

**Comment by cheako** [comment]
I don't think one replaces the other: R2D2 requires the connection type to be `'static`.

If we define `use` such that it's the state every value in the `Pool` is not currently in...  Then I guess that's true?  I'm in favor of expanding the term `use` to being anything currently allocated, and that breaks the inherent circular logic in the previous statement.  It's true, you could bend over backwards to come up with a definition for `use` that would exclude the definition in the OP and include the definition here.  I challenge you to do so without invoking some "unique" mental gymnastics.
